spring.application.name=alimtalk

spring.datasource.url=jdbc:h2:mem:alimtalk
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

admin.api-key=${ADMIN_API_KEY:da049c7249f0eef6d161cdbe6614499d}
